In [1]:

import pandas as pd

In [2]:
# end_to_end_flow.csv is a csv extracted usigng live data capture, this is 1 flow of the data, the onboardig webpage has 5 different sections each having different branching section(YES?NO(2^n possibilities)), different repeatable sections (Benificiary, jooint partner,, isbeneficiary, permananentaddresssameasmailing and many more (n! factorial * m possibilities)), and various dropdowns for county, code, occupations, salary range etc. This poses a problem in creating multiple test cases (probablities could exceed millions). A simple example is all_elements.csv(access and have a look) where i have tried to select all elements in the all sections atleast one time for eleemtnname+Action capture, the rult is 745 rows with diffrent eleemtn data+actions+xpaths (even here a few thifns have been left unselected). So it is pretty clear that making different probabilities on all_elements.csv is impossible.

# The suggested solution:
# We provide an LLM model, the all_element.csv as context, the model will learn the grouping (Groups columsn to identify different pages), heirarchy of data flow and subsections+options, semantic relationship of heirarchial flow, branches, repeatable sections and dropdown options. Then we use Advanced prompt engineering and ask the model to generate us a new testcase csv.
# Example. We ask model to create a csv of test case having Gender as male, including 2 benificiary, 3 joint acctount etc etc etc, although a little difficult, this is the best way for a QA to generate different test case scenarios. This will give us multiple csv as needed by the user with different scenarios, sub section , repetiton setions and flow included. All controlable through prompt and not probability.

In [4]:
df = pd.read_csv("../data/samples/End_to_End_path.csv")

In [5]:
import pandas as pd

# Show all columns
pd.set_option('display.max_columns', None)

# Show all rows
pd.set_option('display.max_rows', None)

# Don't truncate column content
pd.set_option('display.max_colwidth', None)

# For scrollable output in Jupyter
pd.set_option('display.width', None)

In [6]:
df

,Unnamed: 0,Group,Element,Action,Value,Strategy,XPath
0,0,Personal Information,firstName,click,NaN,id,"//*[@id=""firstName""]"
1,1,Personal Information,firstName,Input,PRAKYATHMC,id,"//*[@id=""firstName""]"
2,2,Personal Information,email,click,NaN,id,"//*[@id=""email""]"
3,3,Personal Information,email,Input,P@GMAIL.COM,id,"//*[@id=""email""]"
4,4,Personal Information,middleName,click,NaN,id,"//*[@id=""middleName""]"
5,5,Personal Information,middleName,Input,M,id,"//*[@id=""middleName""]"
6,6,Personal Information,mobileNumber,click,NaN,id,"//*[@id=""mobileNumber""]"
7,7,Personal Information,mobileNumber,Input,124-3567,id,"//*[@id=""mobileNumber""]"
8,8,Personal Information,lastName,click,NaN,id,"//*[@id=""lastName""]"
9,9,Personal Information,lastName,Input,CHANDRAN,id,"//*[@id=""lastName""]"
10,10,Personal Information,Select Branch,click,NaN,data-testid,"//*[@data-testid=""dropdown-button""]"
11,11,Personal Information,100 - TECU - MARABELLA BRANCH,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
12,12,Personal Information,Add profile picture,click,NaN,data-testid+text,"//*[@data-testid=""button"" and contains(., ""Add profile picture"")]"
13,13,Personal Information,Upload,click,NaN,data-testid,"//*[@data-testid=""upload-button""]"
14,14,Personal Information,file-upload,click,NaN,id,"//*[@id=""file-upload""]"
15,15,Personal Information,file-upload,Input,C:\fakepath\Screenshot 2026-01-27 at 1.02.56 PM.png,id,"//*[@id=""file-upload""]"
16,16,Personal Information,Save & Continue,click,NaN,data-testid+text,"//*[@data-testid=""button"" and contains(., ""Save & Continue"")]"
17,17,Personal Information,otp-input-0,click,NaN,id,"//*[@id=""otp-input-0""]"
18,18,Personal Information,otp-input-0,Input,1,id,"//*[@id=""otp-input-0""]"
19,19,Personal Information,otp-input-1,Input,2,id,"//*[@id=""otp-input-1""]"
20,20,Personal Information,otp-input-2,Input,1,id,"//*[@id=""otp-input-2""]"
21,21,Personal Information,otp-input-3,Input,2,id,"//*[@id=""otp-input-3""]"
22,22,Personal Information,otp-input-4,Input,1,id,"//*[@id=""otp-input-4""]"
23,23,Personal Information,otp-input-5,Input,2,id,"//*[@id=""otp-input-5""]"
24,24,Personal Information,Verify OTP,click,NaN,data-testid,"//*[@data-testid=""submit-button""]"
25,25,Documents,Choose an option,click,NaN,data-testid,"//*[@data-testid=""dropdown-button""]"
26,26,Documents,Passport,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
27,27,Documents,Select File,click,NaN,data-testid,"//*[@data-testid=""file-upload-label""]"
28,28,Documents,upload-front-input,click,NaN,id,"//*[@id=""upload-front-input""]"
29,29,Documents,upload-front-input,Input,C:\fakepath\AVINASH_PASS.png,id,"//*[@id=""upload-front-input""]"
30,30,Documents,Continue,click,NaN,data-testid,"//*[@data-testid=""continue-button""]"
31,31,Documents,Choose an option,click,NaN,data-testid,"//*[@data-testid=""dropdown-button""]"
32,32,Documents,National Identification Card,click,NaN,data-testid,"//*[@data-testid=""option-1""]"
33,33,Documents,Upload Front of ID,click,NaN,data-testid,"//*[@data-testid=""file-upload-label""]"
34,34,Documents,upload-front-input,click,NaN,id,"//*[@id=""upload-front-input""]"
35,35,Documents,upload-front-input,Input,C:\fakepath\DAVID_N_F.png,id,"//*[@id=""upload-front-input""]"
36,36,Documents,Upload Back of ID,click,NaN,data-testid,"//*[@data-testid=""file-upload-back-label""]"
37,37,Documents,upload-back-input,click,NaN,id,"//*[@id=""upload-back-input""]"
38,38,Documents,upload-back-input,Input,C:\fakepath\DAVID_N_B.png,id,"//*[@id=""upload-back-input""]"
39,39,Documents,Continue,click,NaN,data-testid,"//*[@data-testid=""continue-button""]"
40,40,Documents,Choose an option,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/button[1]
41,41,Documents,FLOW BILL,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
42,42,Documents,Select File,click,NaN,data-testid,"//*[@data-testid=""file-upload-label""]"
43,43,Documents,upload-front-input,click,NaN,id,"//*[@id=""upload-front-input""]"
44,44,Documents,upload-front-input,Input,C:\fakepath\FlowBill.jpg,id,"//*[@id=""upload-front-input""]"
45,45,Documents,mailingCity,click,NaN,id,"//*[@id=""mailingCity""]"
46,46,Documents,mailingCity,Input,TRINCITY,id,"//*[@id=""mailingCity""]"
47,47,Documents,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]/label[1]/div[1]/div[1]
48,48,Documents,permanentAddressSameAsMailing,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]/label[1]/input[1]
49,49,Documents,permanentAddressSameAsMailing,Input,true,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]/label[1]/input[1]
50,50,Documents,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/div[2]/div[1]/label[1]/div[1]/div[1]
51,51,Documents,utilityDocOption,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/div[2]/div[1]/label[1]/input[1]
52,52,Documents,utilityDocOption,Input,true,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/div[2]/div[1]/label[1]/input[1]
53,53,Documents,Save and Continue,click,NaN,data-testid,"//*[@data-testid=""save-and-continue-button""]"
54,54,Additional Details,Select Employment Status,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Select Employment Status"")]"
55,55,Additional Details,FULL TIME PERMANENT,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
56,56,Additional Details,Select Employer,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Select Employer"")]"
57,57,Additional Details,ABT ENGINEERS & CONSTRUCTORS L,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
58,58,Additional Details,:rt:-year,click,NaN,id,"//*[@id="":rt:-year""]"
59,59,Additional Details,occupation,click,NaN,id,"//*[@id=""occupation""]"
60,60,Additional Details,occupation,Input,ENGINEER,id,"//*[@id=""occupation""]"
61,61,Additional Details,Choose sector,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Choose sector"")]"
62,62,Additional Details,PRIVATE SECTOR,click,NaN,data-testid,"//*[@data-testid=""option-1""]"
63,63,Additional Details,Choose Employment Type,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Choose Employment Type"")]"
64,64,Additional Details,Agricultural,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
65,65,Additional Details,employerAddressLine1,click,NaN,id,"//*[@id=""employerAddressLine1""]"
66,66,Additional Details,employerAddressLine1,Input,7 NORTHAM ROAD,id,"//*[@id=""employerAddressLine1""]"
67,67,Additional Details,employerCity,click,NaN,id,"//*[@id=""employerCity""]"
68,68,Additional Details,employerCity,Input,TRINCITY,id,"//*[@id=""employerCity""]"
69,69,Additional Details,Choose Country,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Choose Country"")]"
70,70,Additional Details,TRINIDAD AND TOBAGO,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
71,71,Additional Details,workPhoneNo,click,NaN,id,"//*[@id=""workPhoneNo""]"
72,72,Additional Details,workPhoneNo,Input,324-3546,id,"//*[@id=""workPhoneNo""]"
73,73,Additional Details,Choose an option,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Choose an option"")]"
74,74,Additional Details,"$12,001-$17,000",click,NaN,data-testid,"//*[@data-testid=""option-0""]"
75,75,Additional Details,Salary Frequency,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Salary Frequency"")]"
76,76,Additional Details,ANNUALLY,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
77,77,Additional Details,salary,click,NaN,name,"//input[@name=""salary""]"
78,78,Additional Details,salary,Input,"$ 13,000.00",name,"//input[@name=""salary""]"
79,79,Additional Details,Account Funded,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Account Funded"")]"
80,80,Additional Details,Via Salary,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
81,81,Additional Details,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/div[1]
82,82,Additional Details,nationalOfTTPrimary,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/input[1]
83,83,Additional Details,nationalOfTTPrimary,Input,true,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/input[1]
84,84,Additional Details,placeOfBirth,click,NaN,id,"//*[@id=""placeOfBirth""]"
85,85,Additional Details,placeOfBirth,Input,TRINCITY,id,"//*[@id=""placeOfBirth""]"
86,86,Additional Details,Country of birth,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Country of birth"")]"
87,87,Additional Details,TRINIDAD AND TOBAGO,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
88,88,Additional Details,Yes,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/label[1]
89,89,Additional Details,nationalOfTTSecondary,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/label[1]/input[1]
90,90,Additional Details,nationalOfTTSecondary,Input,true,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/label[1]/input[1]
91,91,Additional Details,Marital Status,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Marital Status"")]"
92,92,Additional Details,SINGLE,click,NaN,data-testid,"//*[@data-testid=""option-5""]"
93,93,Additional Details,Highest Level of Education,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-text"" and contains(., ""Highest Level of Education"")]"
94,94,Additional Details,POSTGRADUATE DEGREE,click,NaN,data-testid,"//*[@data-testid=""option-1""]"
95,95,Additional Details,Communication Method,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Communication Method"")]"
96,96,Additional Details,Email,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
97,97,Additional Details,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[6]/div[1]/div[2]/div[1]/label[2]/div[1]/div[1]
98,98,Additional Details,memberOfOtherCreditUnion,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[6]/div[1]/div[2]/div[1]/label[2]/input[1]
99,99,Additional Details,memberOfOtherCreditUnion,Input,false,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[6]/div[1]/div[2]/div[1]/label[2]/input[1]
100,100,Additional Details,Save & Continue,click,NaN,data-testid+text,"//*[@data-testid=""button"" and contains(., ""Save & Continue"")]"
101,101,Other Products,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/div[1]/div[1]
102,102,Other Products,hasBeneficiary,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/input[1]
103,103,Other Products,hasBeneficiary,Input,true,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/input[1]
104,104,Other Products,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/label[3]/div[1]/div[1]
105,105,Other Products,documentType,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/label[3]/input[1]
106,106,Other Products,documentType,Input,BENEFICIARY-PASSPORT,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/label[3]/input[1]
107,107,Other Products,Select Document,click,NaN,class,"//label[contains(@class, ""rounded"")]"
108,108,Other Products,upload-input,click,NaN,id,"//*[@id=""upload-input""]"
109,109,Other Products,upload-input,Input,C:\fakepath\AVINASH_PASS.png,id,"//*[@id=""upload-input""]"
110,110,Other Products,beneficiaryMobileNo,click,NaN,id,"//*[@id=""beneficiaryMobileNo""]"
111,111,Other Products,beneficiaryMobileNo,Input,567-7777,id,"//*[@id=""beneficiaryMobileNo""]"
112,112,Other Products,Select relation,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Select relation"")]"
113,113,Other Products,Brother,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
114,114,Other Products,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/label[1]/div[1]
115,115,Other Products,hasJointPartner,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/label[1]/input[1]
116,116,Other Products,hasJointPartner,Input,true,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/label[1]/input[1]
117,117,Other Products,path,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/svg[1]/path[1]
118,118,Other Products,customerId,click,NaN,id,"//*[@id=""customerId""]"
119,119,Other Products,customerId,Input,121668,id,"//*[@id=""customerId""]"
120,120,Other Products,:r1l:-year,click,NaN,id,"//*[@id="":r1l:-year""]"
121,121,Other Products,Search,click,NaN,data-testid+text,"//*[@data-testid=""button"" and contains(., ""Search"")]"
122,122,Other Products,Select relation,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Select relation"")]"
123,123,Other Products,Brother,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
124,124,Other Products,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[35]/div[1]/div[1]/label[3]/div[1]/div[1]
125,125,Other Products,jointPartnerDocumentType,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[35]/div[1]/div[1]/label[3]/input[1]
126,126,Other Products,jointPartnerDocumentType,Input,JOINT-PARTNER-PASSPORT,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[35]/div[1]/div[1]/label[3]/input[1]
127,127,Other Products,Select Document,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[35]/div[2]/div[3]/div[1]/label[1]
128,128,Other Products,jp-upload-input,click,NaN,id,"//*[@id=""jp-upload-input""]"
129,129,Other Products,jp-upload-input,Input,C:\fakepath\AVINASH_PASS.png,id,"//*[@id=""jp-upload-input""]"
130,130,Other Products,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/label[1]/div[1]/div[1]
131,131,Other Products,isApplyingForLincuCardApplication,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/label[1]/input[1]
132,132,Other Products,isApplyingForLincuCardApplication,Input,true,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/label[1]/input[1]
133,133,Other Products,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/label[1]/div[1]/div[1]
134,134,Other Products,isApplyingForFipApplication,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/label[1]/input[1]
135,135,Other Products,isApplyingForFipApplication,Input,true,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/label[1]/input[1]
136,136,Other Products,Choose an option,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Choose an option"")]"
137,137,Other Products,Plan A,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
138,138,Other Products,deductionTypeDesc,click,NaN,name,"//input[@name=""deductionTypeDesc""]"
139,139,Other Products,deductionTypeDesc,Input,True,name,"//input[@name=""deductionTypeDesc""]"
140,140,Other Products,Select,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[10]/div[1]/div[1]/button[1]
141,141,Other Products,1,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
142,142,Other Products,Choose an option,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[11]/div[1]/div[2]/div[1]/button[1]
143,143,Other Products,Passport,click,NaN,data-testid,"//*[@data-testid=""option-2""]"
144,144,Other Products,Select Document,click,NaN,class,"//label[contains(@class, ""hover:bg-[#cf6d18]"")]"
145,145,Other Products,upload-input-0,click,NaN,id,"//*[@id=""upload-input-0""]"
146,146,Other Products,upload-input-0,Input,C:\fakepath\AVINASH_PASS.png,id,"//*[@id=""upload-input-0""]"
147,147,Other Products,address-0,click,NaN,id,"//*[@id=""address-0""]"
148,148,Other Products,address-0,Input,71 NORTHAM ROAD,id,"//*[@id=""address-0""]"
149,149,Other Products,phoneNumber-0,click,NaN,id,"//*[@id=""phoneNumber-0""]"
150,150,Other Products,phoneNumber-0,Input,333-3333,id,"//*[@id=""phoneNumber-0""]"
151,151,Other Products,Choose an option,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Choose an option"")]"
152,152,Other Products,Parent / Parent-in-Law,click,NaN,data-testid,"//*[@data-testid=""option-0""]"
153,153,Other Products,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/label[1]/div[1]/div[1]
154,154,Other Products,hasRecommender,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/label[1]/input[1]
155,155,Other Products,hasRecommender,Input,true,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/label[1]/input[1]
156,156,Other Products,groupHealth,click,NaN,name,"//input[@name=""groupHealth""]"
157,157,Other Products,groupHealth,Input,True,name,"//input[@name=""groupHealth""]"
158,158,Other Products,div,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[6]/div[2]/div[3]/div[1]/div[1]/label[1]/div[1]/div[1]
159,159,Other Products,isSpouseCoveredByOtherPlan,click,NaN,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[6]/div[2]/div[3]/div[1]/div[1]/label[1]/input[1]
160,160,Other Products,isSpouseCoveredByOtherPlan,Input,true,absolute,/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[6]/div[2]/div[3]/div[1]/div[1]/label[1]/input[1]
161,161,Other Products,planName,click,NaN,id,"//*[@id=""planName""]"
162,162,Other Products,planName,Input,ABCD,id,"//*[@id=""planName""]"
163,163,Other Products,insuranceCompany,click,NaN,id,"//*[@id=""insuranceCompany""]"
164,164,Other Products,insuranceCompany,Input,LIFE,id,"//*[@id=""insuranceCompany""]"
165,165,Other Products,Select Bank,click,NaN,data-testid+text,"//*[@data-testid=""dropdown-button"" and contains(., ""Select Bank"")]"
166,166,Other Products,FIRST CITIZENS BANK,click,NaN,data-testid,"//*[@data-testid=""option-0""]"

In [ ]:
df = df[["Group", "Element","Action","Value"]]

#replace NaN with Clicks
df['Value'] = df.apply(
    lambda row: 'Click' if row['Action'] == 'click' else row['Value'],
    axis=1
)

In [ ]:
df

In [ ]:
# converting all_elements.csv to json

import json
import re
from collections import defaultdict

#Load the csv
df = pd.read_csv("../data/samples/All_elements_flow.csv")
df

In [4]:
# generated edge case data

data = pd.read_csv("../data/captures/end_to_end_flow_path_output.csv")
# Show all columns
pd.set_option('display.max_columns', None)

# Optional: also show all rows and full width
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [5]:
data

,Group,Personal Information,Personal Information.1,Personal Information.2,Personal Information.3,Personal Information.4,Personal Information.5,Personal Information.6,Personal Information.7,Personal Information.8,Personal Information.9,Personal Information.10,Personal Information.11,Personal Information.12,Personal Information.13,Personal Information.14,Personal Information.15,Personal Information.16,Personal Information.17,Personal Information.18,Personal Information.19,Personal Information.20,Personal Information.21,Personal Information.22,Personal Information.23,Personal Information.24,Documents,Documents.1,Documents.2,Documents.3,Documents.4,Documents.5,Documents.6,Documents.7,Documents.8,Documents.9,Documents.10,Documents.11,Documents.12,Documents.13,Documents.14,Documents.15,Documents.16,Documents.17,Documents.18,Documents.19,Documents.20,Documents.21,Documents.22,Documents.23,Documents.24,Documents.25,Documents.26,Documents.27,Documents.28,Additional Details,Additional Details.1,Additional Details.2,Additional Details.3,Additional Details.4,Additional Details.5,Additional Details.6,Additional Details.7,Additional Details.8,Additional Details.9,Additional Details.10,Additional Details.11,Additional Details.12,Additional Details.13,Additional Details.14,Additional Details.15,Additional Details.16,Additional Details.17,Additional Details.18,Additional Details.19,Additional Details.20,Additional Details.21,Additional Details.22,Additional Details.23,Additional Details.24,Additional Details.25,Additional Details.26,Additional Details.27,Additional Details.28,Additional Details.29,Additional Details.30,Additional Details.31,Additional Details.32,Additional Details.33,Additional Details.34,Additional Details.35,Additional Details.36,Additional Details.37,Additional Details.38,Additional Details.39,Additional Details.40,Additional Details.41,Additional Details.42,Additional Details.43,Additional Details.44,Additional Details.45,Additional Details.46,Other Products,Other Products.1,Other Products.2,Other Products.3,Other Products.4,Other Products.5,Other Products.6,Other Products.7,Other Products.8,Other Products.9,Other Products.10,Other Products.11,Other Products.12,Other Products.13,Other Products.14,Other Products.15,Other Products.16,Other Products.17,Other Products.18,Other Products.19,Other Products.20,Other Products.21,Other Products.22,Other Products.23,Other Products.24,Other Products.25,Other Products.26,Other Products.27,Other Products.28,Other Products.29,Other Products.30,Other Products.31,Other Products.32,Other Products.33,Other Products.34,Other Products.35,Other Products.36,Other Products.37,Other Products.38,Other Products.39,Other Products.40,Other Products.41,Other Products.42,Other Products.43,Other Products.44,Other Products.45,Other Products.46,Other Products.47,Other Products.48,Other Products.49,Other Products.50,Other Products.51,Other Products.52,Other Products.53,Other Products.54,Other Products.55,Other Products.56,Other Products.57,Other Products.58,Other Products.59,Other Products.60,Other Products.61,Other Products.62,Other Products.63,Other Products.64,Other Products.65,Other Products.66,Other Products.67,Other Products.68,Other Products.69,Other Products.70,Other Products.71,Other Products.72,Other Products.73,Other Products.74,Other Products.75,Other Products.76,Other Products.77,Other Products.78,Other Products.79,Other Products.80,Other Products.81,Other Products.82,Other Products.83,Other Products.84,Other Products.85,Other Products.86,Other Products.87,Other Products.88,Other Products.89,Other Products.90,Other Products.91,Other Products.92,Other Products.93,Other Products.94,Other Products.95,Other Products.96,Other Products.97,Other Products.98,Other Products.99,Other Products.100,Other Products.101,Other Products.102,Other Products.103,Other Products.104,Other Products.105,Other Products.106,Other Products.107,Other Products.108,Other Products.109,Other Products.110,Other Products.111,Other Products.112,Other Products.113,Other Products.114,Other Products.115,Other Products.116,Other Products.117,PEP / FATCA,PEP / FATCA.1,PEP / FATCA.2,PEP / FATCA.3,PEP / FATCA.4,PEP / FATCA.5,PEP / FATCA.6,PEP / FATCA.7,PEP / FATCA.8,PEP / FATCA.9,PEP / FATCA.10,PEP / FATCA.11,PEP / FATCA.12,PEP / FATCA.13,PEP / FATCA.14,PEP / FATCA.15,PEP / FATCA.16,PEP / FATCA.17,PEP / FATCA.18,PEP / FATCA.19,PEP / FATCA.20,PEP / FATCA.21,PEP / FATCA.22,PEP / FATCA.23,PEP / FATCA.24,PEP / FATCA.25,PEP / FATCA.26,PEP / FATCA.27,PEP / FATCA.28,PEP / FATCA.29,PEP / FATCA.30,PEP / FATCA.31,PEP / FATCA.32,PEP / FATCA.33,PEP / FATCA.34,PEP / FATCA.35,PEP / FATCA.36,PEP / FATCA.37,PEP / FATCA.38,PEP / FATCA.39,PEP / FATCA.40,PEP / FATCA.41,PEP / FATCA.42,PEP / FATCA.43,PEP / FATCA.44,PEP / FATCA.45,PEP / FATCA.46,PEP / FATCA.47,PEP / FATCA.48,PDF / Other Details,PDF / Other Details.1,PDF / Other Details.2,PDF / Other Details.3,PDF / Other Details.4,PDF / Other Details.5,PDF / Other Details.6,PDF / Other Details.7,PDF / Other Details.8,PDF / Other Details.9,PDF / Other Details.10,PDF / Other Details.11,PDF / Other Details.12,PDF / Other Details.13,PDF / Other Details.14,PDF / Other Details.15,PDF / Other Details.16,PDF / Other Details.17,PDF / Other Details.18,PDF / Other Details.19,PDF / Other Details.20,PDF / Other Details.21,PDF / Other Details.22,PDF / Other Details.23,PDF / Other Details.24,PDF / Other Details.25,PDF / Other Details.26,PDF / Other Details.27,PDF / Other Details.28,PDF / Other Details.29
0,Description,firstName,firstName,email,email,middleName,middleName,mobileNumber,mobileNumber,lastName,lastName,Select Branch,100 - TECU - MARABELLA BRANCH,Add profile picture,Upload,file-upload,file-upload,Save & Continue,otp-input-0,otp-input-0,otp-input-1,otp-input-2,otp-input-3,otp-input-4,otp-input-5,Verify OTP,Choose an option,Passport,Select File,upload-front-input,upload-front-input,Continue,Choose an option,National Identification Card,Upload Front of ID,upload-front-input,upload-front-input,Upload Back of ID,upload-back-input,upload-back-input,Continue,Choose an option,FLOW BILL,Select File,upload-front-input,upload-front-input,mailingCity,mailingCity,div,permanentAddressSameAsMailing,permanentAddressSameAsMailing,div,utilityDocOption,utilityDocOption,Save and Continue,Select Employment Status,FULL TIME PERMANENT,Select Employer,ABT ENGINEERS & CONSTRUCTORS L,:rt:-year,occupation,occupation,Choose sector,PRIVATE SECTOR,Choose Employment Type,Agricultural,employerAddressLine1,employerAddressLine1,employerCity,employerCity,Choose Country,TRINIDAD AND TOBAGO,workPhoneNo,workPhoneNo,Choose an option,"$12,001-$17,000",Salary Frequency,ANNUALLY,salary,salary,Account Funded,Via Salary,div,nationalOfTTPrimary,nationalOfTTPrimary,placeOfBirth,placeOfBirth,Country of birth,TRINIDAD AND TOBAGO,Yes,nationalOfTTSecondary,nationalOfTTSecondary,Marital Status,SINGLE,Highest Level of Education,POSTGRADUATE DEGREE,Communication Method,Email,div,memberOfOtherCreditUnion,memberOfOtherCreditUnion,Save & Continue,div,hasBeneficiary,hasBeneficiary,div,documentType,documentType,Select Document,upload-input,upload-input,beneficiaryMobileNo,beneficiaryMobileNo,Select relation,Brother,div,hasJointPartner,hasJointPartner,path,customerId,customerId,:r1l:-year,Search,Select relation,Brother,div,jointPartnerDocumentType,jointPartnerDocumentType,Select Document,jp-upload-input,jp-upload-input,div,isApplyingForLincuCardApplication,isApplyingForLincuCardApplication,div,isApplyingForFipApplication,isApplyingForFipApplication,Choose an option,Plan A,deductionTypeDesc,deductionTypeDesc,Select,1,Choose an option,Passport,Select Document,upload-input-0,upload-input-0,address-0,address-0,phoneNumber-0,phoneNumber-0,Choose an option,Parent / Parent-in-Law,div,hasRecommender,hasRecommender,groupHealth,groupHealth,div,isSpouseCoveredByOtherPlan,isSpouseCoveredByOtherPlan,planName,planName,insuranceCompany,insuranceCompany,Select Bank,FIRST CITIZENS BANK,branchName,branchName,accountNo,accountNo,div,accountType,accountType,div,addDependent,addDependent,div,dependent-0-isTecuMember,dependent-0-isTecuMember,Choose an option,Passport,Select File,dependent-0-upload,dependent-0-upload,circle,customerId,customerId,:r2h:-year,Search,Select relation,Spouse,div,beneficiary,beneficiary,div,beneficiary-0-isTecuMember,beneficiary-0-isTecuMember,Choose an option,Passport,Select File,beneficiary-0-upload,beneficiary-0-upload,beneficiaryMobileNo0,beneficiaryMobileNo0,beneficiaryAddressLine10,beneficiaryAddressLine10,beneficiaryCity0,beneficiaryCity0,beneficiaryPercentage0,beneficiaryPercentage0,isAllInformationCorrect,isAllInformationCorrect,isTermsAndConditionsAccepted,Accept,Save & Continue,Select relation,Son,Save & Continue,div,isHeadOfState,isHeadOfState,div,isHeadOfGovt,isHeadOfGovt,div,isSenPolitician,isSenPolitician,div,isSenGovtOfficial,isSenGovtOfficial,div,isSenJudicialOfficial,isSenJudicialOfficial,div,isSenMilitaryOfficial,isSenMilitaryOfficial,div,isSenExecSOC,isSenExecSOC,div,isImpPPO,isImpPPO,div,isImmediateFamily,isImmediateFamily,div,isMemberOfSeniorManagement,isMemberOfSeniorManagement,div,isPepAssociate,isPepAssociate,div,isCitizenOfOtherCountry,isCitizenOfOtherCountry,div,isGreenCardHolder,isGreenCardHolder,div,isGranteePOA,isGranteePOA,div,hasStandingInstructIncome,hasStandingInstructIncome,div,isDisclosureTaxResidency,isDisclosureTaxResidency,Save & Continue,View PDF,View PDF,View PDF,View PDF,View PDF,View PDF,View PDF,Select File,1.-job-letter-(less-than-3-months-old),1.-job-letter-(less-than-3-months-old),Select File,2.-pay-slip-(less-than-1-month-old),2.-pay-slip-(less-than-1-month-old),Submit,otp-input-0,otp-input-0,otp-input-1,otp-input-2,otp-input-3,otp-input-4,otp-input-5,Verify OTP,otp-input-0,otp-input-0,otp-input-1,otp-input-2,otp-input-3,otp-input-4,otp-input-5,Verify OTP
1,Action,click,input,click,input,click,input,click,input,click,input,click,click,click,click,click,input,click,click,input,input,input,input,input,input,click,click,click,click,click,input,click,click,click,click,click,input,click,click,input,click,click,click,click,click,input,click,input,click,click,input,click,click,input,click,click,click,click,click,click,click,input,click,click,click,click,click,input,click,input,click,click,click,input,click,click,click,click,click,input,click,click,click,click,input,click,input,click,click,click,click,input,click,click,click,click,click,click,click,click,input,click,click,click,input,click,click,input,click,click,input,click,input,click,click,click,click,input,click,click,input,click,click,click,click,click,click,input,click,click,input,click,click,input,click,click,input,click,click,click,input,click,click,click,click,click,click,input,click,input,click,input,click,click,click,click,input,click,input,click,click,input,click,input,click,input,click,click,click,input,click,input,click,click,input,click,click,input,click,click,input,click,click,click,click,input,click,click,input,click,click,click,click,click,click,input,click,click,input,click,click,click,click,input,click,input,click,input,click,input,click,input,click,input,click,click,click,click,click,click,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,input,click,click,click,click,click,click,click,click,click,click,input,click,click,input,click,click,input,input,input,input,input,input,click,click,input,input,input,input,input,input,click
2,Property,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Strategy,id,id,id,id,id,id,id,id,id,id,data-testid,data-testid,data-testid+text,data-testid,id,id,data-testid+text,id,id,id,id,id,id,id,data-testid,data-testid,data-testid,data-testid,id,id,data-testid,data-testid,data-testid,data-testid,id,id,data-testid,id,id,data-testid,absolute,data-testid,data-testid,id,id,id,id,absolute,absolute,absolute,absolute,absolute,absolute,data-testid,data-testid+text,data-testid,data-testid+text,data-testid,id,id,id,data-testid+text,data-testid,data-testid+text,data-testid,id,id,id,id,data-testid+text,data-testid,id,id,data-testid+text,data-testid,data-testid+text,data-testid,name,name,data-testid+text,data-testid,absolute,absolute,absolute,id,id,data-testid+text,data-testid,absolute,absolute,absolute,data-testid+text,data-testid,data-testid+text,data-testid,data-testid+text,data-testid,absolute,absolute,absolute,data-testid+text,absolute,absolute,absolute,absolute,absolute,absolute,class,id,id,id,id,data-testid+text,data-testid,absolute,absolute,absolute,absolute,id,id,id,data-testid+text,data-testid+text,data-testid,absolute,absolute,absolute,absolute,id,id,absolute,absolute,absolute,absolute,absolute,absolute,data-testid+text,data-testid,name,name,absolute,data-testid,absolute,data-testid,class,id,id,id,id,id,id,data-testid+text,data-testid,absolute,absolute,absolute,name,name,absolute,absolute,absolute,id,id,id,id,data-testid+text,data-testid,id,id,id,id,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,data-testid+text,data-testid,class,id,id,absolute,id,id,id,data-testid+text,data-testid+text,data-testid,absolute,absolute,absolute,absolute,absolute,absolute,data-testid+text,data-testid,absolute,id,id,id,id,id,id,id,id,id,id,name,name,name,text,data-testid+text,data-testid+text,data-testid,data-testid+text,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,data-testid+text,absolute,absolute,absolute,absolute,absolute,absolute,absolute,absolute,id,id,absolute,id,id,data-testid,id,id,id,id,id,id,id,data-testid,id,id,id,id,id,id,id,data-testid

In [12]:
test2_data = pd.read_csv("../data/captures/test2_output.csv")

In [13]:
test2_data

,Group,Personal Info / Documents,Personal Info / Documents.1,Personal Info / Documents.2,Personal Info / Documents.3,Personal Info / Documents.4,Personal Info / Documents.5,Personal Info / Documents.6,Personal Info / Documents.7,Personal Info / Documents.8,Personal Info / Documents.9,Personal Info / Documents.10,Personal Info / Documents.11,Personal Info / Documents.12,Personal Info / Documents.13,Personal Info / Documents.14,Personal Info / Documents.15,Personal Info / Documents.16,Personal Info / Documents.17,Personal Info / Documents.18,Personal Info / Documents.19,Personal Info / Documents.20,Personal Info / Documents.21,Personal Info / Documents.22,Personal Info / Documents.23,Personal Info / Documents.24,Personal Info / Documents.25,Personal Info / Documents.26,Personal Info / Documents.27,Personal Info / Documents.28,Personal Info / Documents.29,Personal Info / Documents.30,Personal Info / Documents.31,Personal Info / Documents.32,Personal Info / Documents.33,Personal Info / Documents.34,Personal Info / Documents.35,Personal Info / Documents.36,Personal Info / Documents.37,Personal Info / Documents.38,Personal Info / Documents.39,Personal Info / Documents.40,Personal Info / Documents.41,Personal Info / Documents.42,Personal Info / Documents.43,Personal Info / Documents.44,Personal Info / Documents.45,Personal Info / Documents.46,Personal Info / Documents.47,Personal Info / Documents.48,Personal Info / Documents.49,Personal Info / Documents.50,Personal Info / Documents.51,Personal Info / Documents.52,Personal Info / Documents.53
0,Description,firstName,firstName,email,email,middleName,middleName,mobileNumber,mobileNumber,lastName,lastName,Select Branch,200 - TECU - COUVA BRANCH,Add profile picture,Upload,file-upload,file-upload,Save & Continue,otp-input-0,otp-input-0,otp-input-1,otp-input-2,otp-input-3,otp-input-4,otp-input-5,Verify OTP,Choose an option,Passport,Select File,upload-front-input,upload-front-input,Continue,Choose an option,National Identification Card,Upload Front of ID,upload-front-input,upload-front-input,Upload Back of ID,upload-back-input,upload-back-input,Continue,Choose an option,FLOW BILL,Select File,upload-front-input,upload-front-input,mailingCity,mailingCity,div,permanentAddressSameAsMailing,permanentAddressSameAsMailing,div,utilityDocOption,utilityDocOption,Save and Continue
1,Action,click,input,click,input,click,input,click,input,click,input,click,click,click,click,click,input,click,click,input,input,input,input,input,input,click,click,click,click,click,input,click,click,click,click,click,input,click,click,input,click,click,click,click,click,input,click,input,click,click,input,click,click,input,click
2,Property,text,text,email,email,text,text,tel,tel,text,text,submit,li,submit,label,file,file,submit,text | max:1,text | max:1,text | max:1,text | max:1,text | max:1,text | max:1,text | max:1,submit,submit,li,label,file,file,submit,submit,li,label,file,file,label,file,file,submit,submit,li,label,file,file,text | max:50,text | max:50,div,radio,radio,div,radio,radio,submit
3,Strategy,id,id,id,id,id,id,id,id,id,id,data-testid,data-testid,data-testid+text,data-testid,id,id,data-testid+text,id,id,id,id,id,id,id,data-testid,data-testid,data-testid,data-testid,id,id,data-testid,data-testid,data-testid,data-testid,id,id,data-testid,id,id,data-testid,absolute,data-testid,data-testid,id,id,id,id,absolute,absolute,absolute,absolute,absolute,absolute,data-testid
4,XPath,"//*[@id=""firstName""]","//*[@id=""firstName""]","//*[@id=""email""]","//*[@id=""email""]","//*[@id=""middleName""]","//*[@id=""middleName""]","//*[@id=""mobileNumber""]","//*[@id=""mobileNumber""]","//*[@id=""lastName""]","//*[@id=""lastName""]","//*[@data-testid=""dropdown-button""]","//*[@data-testid=""option-1""]","//*[@data-testid=""button"" and contains(., ""Add profile picture"")]","//*[@data-testid=""upload-button""]","//*[@id=""file-upload""]","//*[@id=""file-upload""]","//*[@data-testid=""button"" and contains(., ""Save & Continue"")]","//*[@id=""otp-input-0""]","//*[@id=""otp-input-0""]","//*[@id=""otp-input-1""]","//*[@id=""otp-input-2""]","//*[@id=""otp-input-3""]","//*[@id=""otp-input-4""]","//*[@id=""otp-input-5""]","//*[@data-testid=""submit-button""]","//*[@data-testid=""dropdown-button""]","//*[@data-testid=""option-0""]","//*[@data-testid=""file-upload-label""]","//*[@id=""upload-front-input""]","//*[@id=""upload-front-input""]","//*[@data-testid=""continue-button""]","//*[@data-testid=""dropdown-button""]","//*[@data-testid=""option-1""]","//*[@data-testid=""file-upload-label""]","//*[@id=""upload-front-input""]","//*[@id=""upload-front-input""]","//*[@data-testid=""file-upload-back-label""]","//*[@id=""upload-back-input""]","//*[@id=""upload-back-input""]","//*[@data-testid=""continue-button""]",/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/button[1],"//*[@data-testid=""option-0""]","//*[@data-testid=""file-upload-label""]","//*[@id=""upload-front-input""]","//*[@id=""upload-front-input""]","//*[@id=""mailingCity""]","//*[@id=""mailingCity""]",/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]/label[1]/div[1]/div[1],/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]/label[1]/input[1],/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]/label[1]/input[1],/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/div[2]/div[1]/label[1]/div[1]/div[1],/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/div[2]/div[1]/label[1]/input[1],/html/body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/div[2]/div[1]/label[1]/input[1],"//*[@data-testid=""save-and-continue-button""]"
5,Perfect_Template (Valid Flow),Click,CLARK,Click,CLARK@GMAIL.COM,Click,S,Click,745-8962,Click,KENT,Click,Click,Click,Click,Click,C:\fakepath\Screenshot 2026-01-27 at 1.02.56 PM.png,Click,Click,1,2,1,2,1,2,Click,Click,Click,Click,Click,C:\fakepath\AVINASH_PASS.png,Click,Click,Click,Click,Click,C:\fakepath\DAVID_N_F.png,Click,Click,C:\fakepath\DAVID_N_B.png,Click,Click,Click,Click,Click,C:\fakepath\FlowBill.jpg,Click,TRINCITY,Click,Click,true,Click,Click,true,Click
6,firstName (Personal Info / Documents),Click,| @#$%^&*<> | 12345 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,Click,CLARK@GMAIL.COM,Click,S,Click,745-8962,Click,KENT,Click,Click,Click,Click,Click,C:\fakepath\Screenshot 2026-01-27 at 1.02.56 PM.png,Click,Click,1,2,1,2,1,2,Click,Click,Click,Click,Click,C:\fakepath\AVINASH_PASS.png,Click,Click,Click,Click,Click,C:\fakepath\DAVID_N_F.png,Click,Click,C:\fakepath\DAVID_N_B.png,Click,Click,Click,Click,Click,C:\fakepath\FlowBill.jpg,Click,TRINCITY,Click,Click,true,Click,Click,true,Click
7,email (Personal Info / Documents),Click,CLARK,Click,| @#$%^&*<> | 12345 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@gmail.com,Click,S,Click,745-8962,Click,KENT,Click,Click,Click,Click,Click,C:\fakepath\Screenshot 2026-01-27 at 1.02.56 PM.png,Click,Click,1,2,1,2,1,2,Click,Click,Click,Click,Click,C:\fakepath\AVINASH_PASS.png,Click,Click,Click,Click,Click,C:\fakepath\DAVID_N_F.png,Click,Click,C:\fakepath\DAVID_N_B.png,Click,Click,Click,Click,Click,C:\fakepath\FlowBill.jpg,Click,TRINCITY,Click,Click,true,Click,Click,true,Click
8,middleName (Personal Info / Documents),Click,CLARK,Click,CLARK@GMAIL.COM,Click,| @#$%^&*<> | 12345 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,Click,745-8962,Click,KENT,Click,Click,Click,Click,Click,C:\fakepath\Screenshot 2026-01-27 at 1.02.56 PM.png,Click,Click,1,2,1,2,1,2,Click,Click,Click,Click,Click,C:\fakepath\AVINASH_PASS.png,Click,Click,Click,Click,Click,C:\fakepath\DAVID_N_F.png,Click,Click,C:\fakepath\DAVID_N_B.png,Click,Click,Click,Click,Click,C:\fakepath\FlowBill.jpg,Click,TRINCITY,Click,Click,true,Click,Click,true,Click
9,mobileNumber (Personal Info / Documents),Click,CLARK,Click,CLARK@GMAIL.COM,Click,S,Click,| @#$%^&*<> | 12345 | 1234567890123456789012345678901234567890,Click,KENT,Click,Click,Click,Click,Click,C:\fakepath\Screenshot 2026-01-27 at 1.02.56 PM.png,Click,Click,1,2,1,2,1,2,Click,Click,Click,Click,Click,C:\fakepath\AVINASH_PASS.png,Click,Click,Click,Click,Click,C:\fakepath\DAVID_N_F.png,Click,Click,C:\fakepath\DAVID_N_B.png,Click,Click,Click,Click,Click,C:\fakepath\FlowBill.jpg,Click,TRINCITY,Click,Click,true,Click,Click,true,Click
10,lastName (Personal Info / Documents),Click,CLARK,Click,CLARK@GMAIL.COM,Click,S,Click,745-8962,Click,| @#$%^&*<> | 12345 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,Click,Click,Click,Click,Click,C:\fakepath\Screenshot 2026-01-27 at 1.02.56 PM.png,Click,Click,1,2,1,2,1,2,Click,Click,Click,Click,Click,C:\fakepath\AVINASH_PASS.png,Click,Click,Click,Click,Click,C:\fakepath\DAVID_N_F.png,Click,Click,C:\fakepath\DAVID_N_B.png,Click,Click,Click,Click,Click,C:\fakepath\FlowBill.jpg,Click,TRINCITY,Click,Click,true,Click,Click,true,Click
11,mailingCity (Personal Info / Documents),Click,CLARK,Click,CLARK@GMAIL.COM,Click,S,Click,745-8962,Click,KENT,Click,Click,Click,Click,Click,C:\fakepath\Screenshot 2026-01-27 at 1.02.56 PM.png,Click,Click,1,2,1,2,1,2,Click,Click,Click,Click,Click,C:\fakepath\AVINASH_PASS.png,Click,Click,Click,Click,Click,C:\fakepath\DAVID_N_F.png,Click,Click,C:\fakepath\DAVID_N_B.png,Click,Click,Click,Click,Click,C:\fakepath\FlowBill.jpg,Click,| @#$%^&*<> | 12345 | AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,Click,Click,true,Click,Click,true,Click